# your domain
domain: email.iseuwei.tk

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://github.com/Iseuwei/proxypool-1/edit/master/config/source.yaml
